version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "mambaforge-latest"
  apt_packages:
    - libxkbcommon-x11-0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-xfixes0
    - libxcb-xinerama0
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py

conda:
  environment: .rtd-environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      extra_requirements:
        - all
        - docs
      path: .
