version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - libxkbcommon-x11-0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-xfixes0
    - libxcb-xinerama0

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

python:
   install:
     - method: pip
       extra_requirements:
        - all
        - docs
       path: .
