name: CI Workflows

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  core:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libegl-dev
          - libglu1-mesa-dev
          - libx11-xcb-dev
          - libxcb-xinerama0
          - libxi-dev
          - libxkbcommon-dev
          - libxkbcommon-x11-dev
          - libxrender-dev
      envs: |
        - linux: codestyle
          libraries:
          coverage: false
        - linux: py312

  test:
    needs: [core]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libegl-dev
          - libglu1-mesa-dev
          - libx11-xcb-dev
          - libxcb-xinerama0
          - libxi-dev
          - libxkbcommon-dev
          - libxkbcommon-x11-dev
          - libxrender-dev
        brew:
          - enchant
      envs: |
        - linux: py312-docs
          coverage: false
        - macos: py312
        - windows: py312
