name: CI Workflows

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  core:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      libraries: |
        apt:
          - libegl-dev
          - libxcb-icccm4-dev
          - libxcb-image0-dev
          - libxcb-keysyms1-dev
          - libxcb-randr0-dev
          - libxcb-render-util0-dev
          - libxcb-xinerama0
          - libxcb-xinerama0-dev
          - libxkbcommon-x11-dev
      envs: |
        - linux: codestyle
          libraries:
          coverage: false
        - linux: py39

  test:
    needs: [core]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      libraries: |
        apt:
          - libegl-dev
          - libxcb-icccm4-dev
          - libxcb-image0-dev
          - libxcb-keysyms1-dev
          - libxcb-randr0-dev
          - libxcb-render-util0-dev
          - libxcb-xinerama0-dev
          - libxkbcommon-x11-dev
        brew:
          - enchant
      envs: |
        - linux: py310-devdeps
        - linux: py39-docs
          coverage: false
        - macos: py38
        - windows: py39
